name: game_shop_demo_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  shared_preferences: ^0.5.7
  intl: ^0.16.1
  path: ^1.6.2
  path_provider: ^1.6.7
  image_picker: ^0.6.5+3
  uuid: ^2.0.4
  flutter_sticky_header: ^0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/brandLogo.png
   - assets/images/shopOverview.png
   - assets/images/placeholderAvatar.png
   - assets/images/dummyUserAvatar1.png
   - assets/images/dummyUserAvatar2.png
   - assets/images/dummyUserAvatar3.png
   - assets/images/dummyUserAvatar4.png
   - assets/images/dummyUserAvatar5.png
   - assets/images/dummyUserAvatar6.png
   - assets/images/dummyUserAvatar7.png
   - assets/images/dummyUserAvatar8.png
   - assets/images/dummyUserAvatar9.png
   - assets/images/dummyUserAvatar10.png
   - assets/images/dummyUserAvatar11.png
   - assets/images/dummyUserAvatar12.png
   - assets/images/dummyUserAvatar13.png
   - assets/images/dummyUserAvatar14.png
   - assets/images/dummyEventCategory.png
   - assets/images/dummyFoodCategory.png
   - assets/images/dummyProductCategory.png
   - assets/images/dummyBranchCategory.png
   - assets/images/dummyBoardGame.png
   - assets/images/dummyComicBook.png
   - assets/images/dummyComputerGame.png
   - assets/images/dummyCosplay.png
   - assets/images/dummyFigure.png
   - assets/images/dummyFRP.png
   - assets/images/dummyMagic.png
   - assets/images/dummyYuGiOh.png
   - assets/images/dummyTomatoSalad.png
   - assets/images/dummyPurslaneSalad.png
   - assets/images/dummyLabadaSalad.png
   - assets/images/dummyKinoaSalad.png
   - assets/images/dummyMushroomSalad.png
   - assets/images/dummyPennePasta.png
   - assets/images/dummyMeatballPasta.png
   - assets/images/dummyMargheritaPizza.png
   - assets/images/dummyWater.png
   - assets/images/dummyToblerone.png
   - assets/images/dummyBounty.png
   - assets/images/dummyKitKat.png
   - assets/images/dummySnickers.png
   - assets/images/dummyMars.png
   - assets/images/dummyTwix.png
   - assets/images/dummyMnM.png
   - assets/images/dummyCrunch.png
   - assets/images/dummyPringles.png
   - assets/images/dummyCheetos.png
   - assets/images/dummyDoritos.png
   - assets/images/dummyLays.png
   - assets/images/dummyIkoria.png
   - assets/images/dummyTheros.png
   - assets/images/dummyEldraine.png
   - assets/images/dummy2020.png
   - assets/images/dummySpark.png
   - assets/images/dummyAllegiance.png
   - assets/images/dummyGuild.png
   - assets/images/dummy2019.png
   - assets/images/dummyAdventure.png
   - assets/images/dummyFerocity.png
   - assets/images/dummyIkoriaBundle.png
   - assets/images/dummyIkoriaBooster.png
   - assets/images/dummyIkoriaBoosterBox1.png
   - assets/images/dummyIkoriaBoosterBox2.png
   - assets/images/dummyTherosBundle.png
   - assets/images/dummyTherosBoosterBox1.png
   - assets/images/dummyTherosBoosterBox2.png
   - assets/images/dummyTherosDeck.png
   - assets/images/dummyThroneBundle.png
   - assets/images/dummyThroneBoosterBox.png
   - assets/images/dummyThroneBooster1.png
   - assets/images/dummyThroneBooster2.png
   - assets/images/dummyThroneBooster3.png
   - assets/images/dummyThroneDeck.png
   - assets/images/dummy2020Bundle.png
   - assets/images/dummy2020BoosterBox.png
   - assets/images/dummySparkBundle.png
   - assets/images/dummySparkBooster.png
   - assets/images/dummySparkBoosterBox.png
   - assets/images/dummyRavnicaBundle.png
   - assets/images/dummyRavnicaBoosterBox.png
   - assets/images/dummyGuildBundle.png
   - assets/images/dummyGuildBoosterBox.png
   - assets/images/dummyGuildGuildKit.png
   - assets/images/dummyMagicBundle.png
   - assets/images/dummyMagicBooster.png
   - assets/images/dummyMagicBoosterBox.png
   - assets/images/dummyMagicDeck.png
   - assets/images/dummyMagicGuildKit.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
